services:
  haskell-new:
    image: haskell-image
    entrypoint: 
      - stack
      - new
      - ${PROJECT_NAME}
      - --bare
      - --force
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
  haskell-dev:
    image: haskell-image
    entrypoint: 
      - bash
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
